version: "2"
services:
    dockerbox:
        image: blendmarketing/dockerbox 
        command: "tail -f /dev/null"
        hostname: dockerbox
        cpu_quota: 5000
        ports:
            - "22:22"
            - "80:80"
        volumes:
            - docker-library:/var/lib/docker
            - ~/code:/home/user/code
            - ~/go/src:/home/user/go/src
            - ~/.ssh:/home/user/.ssh
        working_dir: /home/user/code
        privileged: true
        restart: always
    dnsmasq:
        image: andyshinn/dnsmasq
        restart: always
        ports: 
         - "53535:53/tcp"
         - "53535:53/udp"
        cap_add:
           - NET_ADMIN
        command: "--address=/dev/192.168.57.1"
volumes:
    docker-library:
