version: "3"
services:
    dockerbox:
        image: blendmarketing/dockerbox 
        command: "tail -f /dev/null"
        hostname: dockerbox
        ports:
            - "22:22"
            - "80:80"
            - "53535:53/tcp"
            - "53535:53/udp"
        volumes:
            - docker-library:/var/lib/docker
            - ~/code:/home/user/code
            - ~/go/src:/home/user/go/src
            - ~/.ssh:/home/user/.ssh
        working_dir: /home/user/code
        privileged: true
        restart: always
volumes:
  docker-library:
