version: "3"
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
        restart: always
    dnsmasq:
        image: andyshinn/dnsmasq
        restart: always
        ports: 
            - "53535:53/tcp"
            - "53535:53/udp"
        cap_add:
            - NET_ADMIN
        command: "--address=/dev/192.168.57.1"
networks:
    default:
        external:
            name: dockerbox
